spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/job-offers

job-offers:
  offer:
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057
          connection-timeout: 1000
          read-timeout: 1000
